blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/kpritam/gremlin-mcp/discussions
    about: Ask questions, share ideas, and discuss the project
  - name: 🔒 Security Vulnerability (Private)
    url: https://github.com/kpritam/gremlin-mcp/security/advisories/new
    about: Report sensitive security vulnerabilities privately
  - name: 📖 Documentation
    url: https://github.com/kpritam/gremlin-mcp#readme
    about: Read the documentation and troubleshooting guide